# Site settings
title:       Cast the code
email:       theshallowbay@outlook.com
author:      Shallow Bay
description: "Ten grandes ideas, escribe código y comparte el conocimiento. Blog de desarrollo de software de Shallow Bay."
baseurl:     ""
url:         "http://theshallowbay.github.io"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-72966006-3
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: true
enable_anchorjs: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: shallowware

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number:

# Social icons
github_username: theshallowbay
bitbucket_username:
stackoverflow_id:
twitter_username:
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'más antiguo'
    older: 'más reciente'
  share_buttons:
    text:         'Compartir esto'
    facebook:     'Compartir en Facebook'
    twitter:      'Compartir en Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Compartir en Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Al día'
    minute_read:    'minutos leídos'
    related_posts:  'Publicaciones relacionadas'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Correo electrónico'
    content:  '¿Que te gustaría decirnos?'
    subject:  'Describe tus opiniones'
    submit:   'Enviar'
    ajax:
      sending:  'enviando..'
      sent:     '¡Enviado!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
